"""
路径配置模块

所有路径由启动器通过环境变量传入，后端直接读取，不自行计算。
"""

import os
from pathlib import Path


# ===== 环境变量名称常量 =====
ENV_PROJECT_DIR  = "AI_NOVELIST_PROJECT_DIR"
ENV_DATA_DIR     = "AI_NOVELIST_DATA_DIR"
ENV_BIN_DIR      = "AI_NOVELIST_BIN_DIR"
ENV_ENV_FILE     = "AI_NOVELIST_ENV_FILE"
ENV_CONFIG_DIR   = "AI_NOVELIST_CONFIG_DIR"
ENV_DB_DIR       = "AI_NOVELIST_DB_DIR"
ENV_CHROMADB_DIR = "AI_NOVELIST_CHROMADB_DIR"
ENV_UPLOADS_DIR  = "AI_NOVELIST_UPLOADS_DIR"
ENV_TEMP_DIR     = "AI_NOVELIST_TEMP_DIR"
ENV_SKILLS_DIR   = "AI_NOVELIST_SKILLS_DIR"
ENV_AUTH_DIR     = "AI_NOVELIST_AUTH_DIR"
ENV_STATIC_DIR   = "AI_NOVELIST_STATIC_DIR"
ENV_DB_DIR       = "AI_NOVELIST_DB_DIR"
ENV_CHROMADB_DIR = "AI_NOVELIST_CHROMADB_DIR"
ENV_UPLOADS_DIR  = "AI_NOVELIST_UPLOADS_DIR"
ENV_TEMP_DIR     = "AI_NOVELIST_TEMP_DIR"
ENV_SKILLS_DIR   = "AI_NOVELIST_SKILLS_DIR"
ENV_AUTH_DIR     = "AI_NOVELIST_AUTH_DIR"

# 具体文件
ENV_CONVERSATIONS_DB = "AI_NOVELIST_CONVERSATIONS_DB"
ENV_AUTH_TOKEN_FILE  = "AI_NOVELIST_AUTH_TOKEN_FILE"

# 可执行文件
ENV_GIT_EXECUTABLE  = "AI_NOVELIST_GIT_EXECUTABLE"
ENV_NODE_EXECUTABLE = "AI_NOVELIST_NODE_EXECUTABLE"
ENV_NPM_EXECUTABLE  = "AI_NOVELIST_NPM_EXECUTABLE"
ENV_RG_EXECUTABLE   = "AI_NOVELIST_RG_EXECUTABLE"

# 依赖目录
ENV_VENV_DIR    = "AI_NOVELIST_VENV_DIR"
ENV_MODULES_DIR = "AI_NOVELIST_MODULES_DIR"


def get_env_or_raise(key: str) -> str:
    """从环境变量读取，不存在则抛出异常"""
    value = os.environ.get(key)
    if value is None:
        raise RuntimeError(
            f"缺少必需的环境变量 {key}，请通过启动器启动应用"
        )
    return value
