// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthGetStatus() {
  return window['go']['main']['App']['AuthGetStatus']();
}

export function AuthGetUserInfo() {
  return window['go']['main']['App']['AuthGetUserInfo']();
}

export function AuthLogin(arg1, arg2) {
  return window['go']['main']['App']['AuthLogin'](arg1, arg2);
}

export function AuthLogout() {
  return window['go']['main']['App']['AuthLogout']();
}

export function AuthRegister(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthRegister'](arg1, arg2, arg3);
}

export function AuthResetPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthResetPassword'](arg1, arg2, arg3);
}

export function AuthSendResetCode(arg1) {
  return window['go']['main']['App']['AuthSendResetCode'](arg1);
}

export function AuthSendVerifyCode(arg1) {
  return window['go']['main']['App']['AuthSendVerifyCode'](arg1);
}

export function AutoCheckUpdate() {
  return window['go']['main']['App']['AutoCheckUpdate']();
}

export function BackendRunning() {
  return window['go']['main']['App']['BackendRunning']();
}

export function BackendStart() {
  return window['go']['main']['App']['BackendStart']();
}

export function BackendStop() {
  return window['go']['main']['App']['BackendStop']();
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function FrontendRunning() {
  return window['go']['main']['App']['FrontendRunning']();
}

export function FrontendStart() {
  return window['go']['main']['App']['FrontendStart']();
}

export function FrontendStop() {
  return window['go']['main']['App']['FrontendStop']();
}

export function GetGitServerAddress() {
  return window['go']['main']['App']['GetGitServerAddress']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GitBranches() {
  return window['go']['main']['App']['GitBranches']();
}

export function GitCheckout(arg1) {
  return window['go']['main']['App']['GitCheckout'](arg1);
}

export function GitCreateBranch(arg1) {
  return window['go']['main']['App']['GitCreateBranch'](arg1);
}

export function GitDualCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitDualCheckout'](arg1, arg2);
}

export function GitDualGraph(arg1) {
  return window['go']['main']['App']['GitDualGraph'](arg1);
}

export function GitHistory(arg1) {
  return window['go']['main']['App']['GitHistory'](arg1);
}

export function GitSwitchBranch(arg1) {
  return window['go']['main']['App']['GitSwitchBranch'](arg1);
}

export function IsMainProgramRunning() {
  return window['go']['main']['App']['IsMainProgramRunning']();
}

export function IsProjectDeployed() {
  return window['go']['main']['App']['IsProjectDeployed']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function Logf(arg1, arg2) {
  return window['go']['main']['App']['Logf'](arg1, arg2);
}

export function OpenWebviewTab(arg1, arg2) {
  return window['go']['main']['App']['OpenWebviewTab'](arg1, arg2);
}

export function PrepareEnvironment() {
  return window['go']['main']['App']['PrepareEnvironment']();
}

export function Progress(arg1) {
  return window['go']['main']['App']['Progress'](arg1);
}

export function StartGitServer() {
  return window['go']['main']['App']['StartGitServer']();
}

export function StopGitServer() {
  return window['go']['main']['App']['StopGitServer']();
}

export function SyncProject() {
  return window['go']['main']['App']['SyncProject']();
}
