// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {gitman} from '../models';

export function AutoCheckUpdate():Promise<void>;

export function BackendRunning():Promise<boolean>;

export function BackendStart():Promise<void>;

export function BackendStop():Promise<void>;

export function CheckUpdate():Promise<updater.UpdateStatus>;

export function Cleanup():Promise<void>;

export function FrontendRunning():Promise<boolean>;

export function FrontendStart():Promise<void>;

export function FrontendStop():Promise<void>;

export function GetGitServerAddress():Promise<string>;

export function GetLogs():Promise<string>;

export function GetVersion():Promise<string>;

export function GitBranches():Promise<Array<gitman.BranchInfo>>;

export function GitCheckout(arg1:string):Promise<void>;

export function GitCreateBranch(arg1:string):Promise<void>;

export function GitFullGraph(arg1:number):Promise<Array<gitman.CommitDetail>>;

export function GitHistory(arg1:number):Promise<Array<gitman.CommitDetail>>;

export function GitSwitchBranch(arg1:string):Promise<void>;

export function IsMainProgramRunning():Promise<boolean>;

export function IsProjectDeployed():Promise<boolean>;

export function LoadConfig():Promise<updater.Config>;

export function Logf(arg1:string,arg2:Array<any>):Promise<void>;

export function OpenWebviewTab(arg1:string,arg2:string):Promise<void>;

export function PerformUpdate():Promise<void>;

export function PrepareEnvironment():Promise<void>;

export function Progress(arg1:number):Promise<void>;

export function StartGitServer():Promise<void>;

export function StopGitServer():Promise<void>;
